language: node_js
node_js:
- '8'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/doc.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "eWcXkK8u4zafVoj70Q+FKQM+2AHActNa6+ilGA1/YzEhED+vNFNTTCc2RFWv7xWMw9bg9ZRGLAK3uRNFZFKImTcHPgRyl89f4lis5HffOVn9/++l55RofhhpZwkqD2I/mLavCPY/4AkfCO8mz2MztLinA7gssJg9Vak4Y3AlhbClbCHkPhPk/2dHBzIPmDNtjb1K7lHymyNYAUIxLdhg8bYK81lqQKpNH81OeQDNsXy6aDKWCZHrHLO6Zrsn96PaycxNt2wCKuxltXyFMCvzci0okNKKi+BeZjDVJDCo3wC7xY8AknWMooWWI5Wj0rGPaZ8XEgd68Srv/rxzsMtksCidHVbtq+39HkVrjBZvuhE9JEq5JhFNRFQfekAMbbl6gfWEGB0vXwB0Jr4u2q19DYIijKzyW+CApbadSkR8pZz7qnhdTz4EKFNuI2QALhN/+Uk3TDx57uqSRKD9gLFHVJ6WTNa/4z5CDpKk1UcSkwSdKq8DAahG1wxPYorbITwz6l5C5ECMkMl51mfI2zAmppK6nlLBU/xKe6mJvDS/Yw7XHFhVIU1jpzTz2yGwLAu3likQZigZFX+yA/umEmNUuGZJhGBZZn7NOT2b4qygPMqX50w1pkfGjoxIqxSLptgmoiyEjLdavBgGbUbc3pAwrO0zSwP0aFb1oDEfSldo1PA="
